version: '3.4'

services:
  ai21-ws21-swe-rabbitmq:
    image: rabbitmq:3
    container_name: ai21-ws21-swe-rabbitmq
    # domainname: ai21-ws21-swe-rabbitmq.com
    ports:
      - 5672:5672
      - 15672:15672

  htwai21swegrpb02:
    image: htwai21swegrpb02
    build:
      context: ./file-repository
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ${HOST_VOLUME_PATH}:/api/data
    depends_on:
      - ai21-ws21-swe-rabbitmq # can't really rely on depends_on
    restart: on-failure # try restarting if connection to rabbitmq failed. But connection retrys should be handled in the image itself
  
  ai21-ws21-swe-frontend:
    image: ai21-ws21-swe-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - ai21-ws21-swe-rabbitmq # can't really rely on depends_on

  ai21-ws21-swe-video-builder:
    image: ai21-ws21-swe-video-builder
    build:
      context: ./video-builder
      dockerfile: ./Dockerfile
    depends_on:
      - ai21-ws21-swe-rabbitmq # can't really rely on depends_on
    restart: on-failure # try restarting if connection to rabbitmq failed. But connection retrys should be handled in the image itself
